import React,{useEffect,useMemo,useState}from'react';
import{CalendarDays,Compass,Globe2,Heart,Hotel,MapPin,Navigation,NotebookPen,Plane,Plus,Receipt,ShoppingBag,Trash2,Wallet,X,ArrowRightLeft,CheckCircle2,Circle,Settings,ChevronRight}from'lucide-react';

const KEY='travel-planner-v2';
const THEMES={milk:{bg:'#FCF9F4',card:'#F3EAE0',deep:'#DFCFBE',p:'#B99D83',t:'#554D46'},sage:{bg:'#F5F7F3',card:'#E7EEE5',deep:'#D0DFCC',p:'#829B7C',t:'#465146'},sky:{bg:'#F4F8FA',card:'#E5EFF4',deep:'#CFDFE8',p:'#7FA7B8',t:'#43535B'},butter:{bg:'#FFFDF5',card:'#FFF4D8',deep:'#F5E4AE',p:'#D3AD58',t:'#5D5130'}};
const emptyTrip={id:'default',name:'Fukuoka Trip',city:'Fukuoka',country:'Japan',currency:'JPY',symbol:'¥',start:'2026-08-30',end:'2026-09-03',budget:48000,itinerary:[{date:'8/30',title:'抵達福岡',items:[['14:10','高雄 → 福岡','flight','IT270'],['17:50','抵達福岡機場','transport','前往博多'],['19:00','入住飯店','stay','Check-in'],['20:00','博多車站','place','晚餐、逛街']]},{date:'8/31',title:'天神・太宰府',items:[['09:30','天神地下街','place','逛街'],['12:00','太宰府天滿宮','place','參拜'],['17:00','Blue Bottle Coffee','cafe','咖啡時間']]},{date:'9/1',title:'福岡市區',items:[['10:00','櫛田神社','place','博多散步'],['13:00','LaLaport Fukuoka','shopping','購物'],['18:00','舞鶴公園','place','散步']]},{date:'9/2',title:'近郊',items:[]},{date:'9/3',title:'回程',items:[['11:50','福岡 → 高雄','flight','CI117']]}],expenses:[{id:1,title:'機票',amount:15000,cat:'交通'},{id:2,title:'飯店',amount:5000,cat:'住宿'}],shopping:[{id:1,title:'零食',done:false},{id:2,title:'伴手禮',done:false}],check:[{id:1,title:'護照',done:true},{id:2,title:'E-SIM / 網卡',done:false},{id:3,title:'海外刷卡信用卡',done:true}],saved:[{id:1,title:'太宰府天滿宮',type:'景點'},{id:2,title:'Blue Bottle Coffee',type:'咖啡'}],notes:'把想去的咖啡廳、餐廳與注意事項都記在這裡。',stay:{name:'',address:'',in:'15:00',out:'11:00',wifi:'',door:''}};
function initial(){try{return JSON.parse(localStorage.getItem(KEY))||{trips:[emptyTrip],active:'default',theme:'milk'}}catch{return{trips:[emptyTrip],active:'default',theme:'milk'}}}
const money=n=>Number(n||0).toLocaleString('zh-TW');
const maps=q=>window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q),'_blank');

export default function App(){const[d,setD]=useState(initial),[tab,setTab]=useState('home'),[modal,setModal]=useState(''),[day,setDay]=useState(0),[form,setForm]=useState({name:'',city:'',country:'',currency:'JPY',symbol:'¥',start:'',end:'',budget:''}),[exp,setExp]=useState({title:'',amount:'',cat:'美食'}),[newItem,setNewItem]=useState('');
const trip=d.trips.find(x=>x.id===d.active)||d.trips[0],th=THEMES[d.theme]||THEMES.milk;
useEffect(()=>localStorage.setItem(KEY,JSON.stringify(d)),[d]);
const patch=p=>setD(x=>({...x,trips:x.trips.map(t=>t.id===trip.id?{...t,...p}:t)}));
const spent=useMemo(()=>trip.expenses.reduce((s,e)=>s+Number(e.amount||0),0),[trip.expenses]);
const addTrip=()=>{if(!form.name||!form.city)return;const t={...emptyTrip,id:String(Date.now()),name:form.name,city:form.city,country:form.country||'—',currency:form.currency||'JPY',symbol:form.symbol||'¥',start:form.start,end:form.end,budget:Number(form.budget)||0,itinerary:[],expenses:[],shopping:[],check:[],saved:[],notes:'',stay:{name:'',address:'',in:'',out:'',wifi:'',door:''}};setD(x=>({...x,trips:[...x.trips,t],active:t.id}));setForm({name:'',city:'',country:'',currency:'JPY',symbol:'¥',start:'',end:'',budget:''});setModal('')};
const addExpense=()=>{if(!exp.title||!exp.amount)return;patch({expenses:[{id:Date.now(),title:exp.title,amount:Number(exp.amount),cat:exp.cat},...trip.expenses]});setExp({title:'',amount:'',cat:'美食'});setModal('')};
const addPlace=()=>{if(!newItem)return;const days=[...trip.itinerary];if(!days.length){days.push({date:'Day 1',title:'新行程',items:[]})}days[day%days.length]={...days[day%days.length],items:[...days[day%days.length].items,['—',newItem,'place','']]};patch({itinerary:days});setNewItem('')};
const toggle=(k,id)=>patch({[k]:trip[k].map(x=>x.id===id?{...x,done:!x.done}:x)});
const nav=[['home',Compass,'首頁'],['itinerary',CalendarDays,'行程'],['map',MapPin,'地圖'],['expenses',Wallet,'花費'],['more',NotebookPen,'更多']];
return <div style={{background:th.bg,color:th.t}} className="min-h-screen"><style>{`body{margin:0;font-family:ui-rounded,"PingFang TC","Noto Sans TC",system-ui,sans-serif}button,input,textarea{font:inherit}.hide::-webkit-scrollbar{display:none}`}</style>
<header style={{background:th.card}} className="sticky top-0 z-30 rounded-b-[30px] shadow-sm"><div className="max-w-5xl mx-auto px-5 pt-6 pb-4"><div className="flex items-start justify-between gap-4"><div><div className="text-xs opacity-55 flex items-center gap-1"><Globe2 size={13}/>TRAVEL PLANNER V2</div><h1 className="text-2xl sm:text-3xl font-bold mt-1">{trip.name}</h1><p className="text-sm opacity-60 mt-1 flex items-center gap-1"><MapPin size={14}/>{trip.city}, {trip.country}{trip.start&&<> · {trip.start} — {trip.end}</>}</p></div><button onClick={()=>setModal('trip')} style={{background:th.p}} className="text-white rounded-2xl px-4 py-3 text-sm font-bold flex gap-1 items-center"><Plus size={17}/>新旅行</button></div>{d.trips.length>1&&<div className="flex gap-2 mt-4 overflow-x-auto hide">{d.trips.map(t=><button key={t.id} onClick={()=>setD(x=>({...x,active:t.id}))} className="px-3 py-1.5 rounded-full text-xs whitespace-nowrap" style={{background:t.id===trip.id?th.deep:'#fff'}}>{t.city}</button>)}</div>}</div></header>
<main className="max-w-5xl mx-auto px-4 sm:px-6 py-5 pb-28">{tab==='home'&&<Home trip={trip} th={th} spent={spent} go={setTab}/>} {tab==='itinerary'&&<Itinerary trip={trip} th={th} day={day} setDay={setDay} addPlace={addPlace} newItem={newItem} setNewItem={setNewItem}/>} {tab==='map'&&<MapView trip={trip} th={th}/>} {tab==='expenses'&&<Expenses trip={trip} th={th} spent={spent} add={()=>setModal('expense')}/>} {tab==='more'&&<More trip={trip} th={th} patch={patch} toggle={toggle} setD={setD} d={d}/>}</main>
<nav className="fixed bottom-3 left-1/2 -translate-x-1/2 z-40 w-[calc(100%-24px)] max-w-xl bg-white/90 backdrop-blur-xl rounded-3xl shadow-lg border border-black/5 p-2"><div className="grid grid-cols-5">{nav.map(([id,Icon,l])=><button key={id} onClick={()=>setTab(id)} className="flex flex-col items-center gap-1 py-1.5" style={{color:id===tab?th.p:'#777',fontWeight:id===tab?700:500}}><Icon size={20}/><span className="text-[11px]">{l}</span></button>)}</div></nav>
{modal==='trip'&&<Modal title="建立新的旅行" close={()=>setModal('')}><div className="space-y-3"><Input p="旅行名稱，例如：Tokyo Trip" v={form.name} set={v=>setForm({...form,name:v})}/><div className="grid grid-cols-2 gap-3"><Input p="城市" v={form.city} set={v=>setForm({...form,city:v})}/><Input p="國家 / 地區" v={form.country} set={v=>setForm({...form,country:v})}/></div><div className="grid grid-cols-2 gap-3"><Input p="幣別，例如 JPY / KRW / EUR" v={form.currency} set={v=>setForm({...form,currency:v})}/><Input p="貨幣符號" v={form.symbol} set={v=>setForm({...form,symbol:v})}/></div><div className="grid grid-cols-2 gap-3"><Input p="開始日期 YYYY-MM-DD" v={form.start} set={v=>setForm({...form,start:v})}/><Input p="結束日期 YYYY-MM-DD" v={form.end} set={v=>setForm({...form,end:v})}/></div><Input p="預算（TWD）" type="number" v={form.budget} set={v=>setForm({...form,budget:v})}/><button onClick={addTrip} style={{background:th.p}} className="w-full text-white py-3 rounded-xl font-bold">建立旅行</button></div></Modal>}
{modal==='expense'&&<Modal title="新增花費" close={()=>setModal('')}><div className="space-y-3"><Input p="花費項目" v={exp.title} set={v=>setExp({...exp,title:v})}/><Input p="金額（TWD）" type="number" v={exp.amount} set={v=>setExp({...exp,amount:v})}/><div className="flex flex-wrap gap-2">{['美食','交通','住宿','購物','門票','美容','其他'].map(x=><button key={x} onClick={()=>setExp({...exp,cat:x})} className="px-3 py-2 rounded-xl text-xs" style={{background:exp.cat===x?th.deep:'#f4f4f4'}}>{x}</button>)}</div><button onClick={addExpense} style={{background:th.p}} className="w-full text-white py-3 rounded-xl font-bold">加入花費</button></div></Modal>}</div>}

function Home({trip,th,spent,go}){const pct=trip.budget?Math.min(100,Math.round(spent/trip.budget*100)):0;const today=trip.itinerary[0];return <div className="space-y-5"><section style={{background:th.card}} className="rounded-3xl p-5 sm:p-7 shadow-sm"><div className="flex justify-between"><div><p className="text-sm opacity-55">旅行目的地</p><h2 className="text-3xl font-bold mt-1">{trip.city}</h2><p className="text-sm opacity-60 mt-1">{trip.start||'尚未設定日期'}{trip.end&&` — ${trip.end}`}</p></div><div style={{background:th.p}} className="w-12 h-12 rounded-2xl flex items-center justify-center text-white"><Plane size={23}/></div></div><div className="grid grid-cols-3 gap-2 mt-6"><Stat l="天數" v={trip.itinerary.length||'—'}/><Stat l="預算" v={'NT$'+money(trip.budget)}/><Stat l="已花" v={'NT$'+money(spent)}/></div></section><div className="grid sm:grid-cols-3 gap-3"><Quick I={CalendarDays} t="行程" s={today?.title||'開始安排'} c={()=>go('itinerary')} th={th}/><Quick I={MapPin} t="探索地圖" s="查看旅遊地點" c={()=>go('map')} th={th}/><Quick I={Receipt} t="記一筆" s="管理旅行花費" c={()=>go('expenses')} th={th}/></div><section style={{background:th.card}} className="rounded-3xl p-5 shadow-sm"><p className="text-sm opacity-55">預算使用</p><p className="text-2xl font-bold mt-1">{pct}%</p><div className="h-2 bg-white/70 rounded-full mt-4"><div style={{width:pct+'%',background:th.p}} className="h-full rounded-full"/></div><div className="flex justify-between text-xs opacity-50 mt-2"><span>已使用 NT${money(spent)}</span><span>剩餘 NT${money(Math.max(0,trip.budget-spent))}</span></div></section><Title t="行程預覽" action="查看全部" c={()=>go('itinerary')} th={th}/>{(today?.items||[]).slice(0,4).map((x,i)=><Place key={i} x={x} th={th} city={trip.city}/>)}</div>}
function Itinerary({trip,th,day,setDay,addPlace,newItem,setNewItem}){return <div className="space-y-4"><Title t="行程時間軸" sub="每趟旅行獨立保存" th={th}/><div className="flex gap-2 overflow-x-auto hide">{trip.itinerary.map((x,i)=><button key={i} onClick={()=>setDay(i)} className="px-4 py-2.5 rounded-2xl text-sm whitespace-nowrap" style={{background:i===day?th.p:'#fff',color:i===day?'#fff':th.t}}>{x.date} · {x.title}</button>)}</div>{trip.itinerary.length?<section style={{background:th.card}} className="rounded-3xl p-5 shadow-sm"><div className="flex justify-between items-center mb-5"><div><p className="text-xs opacity-50">Day {day+1}</p><h2 className="text-2xl font-bold">{trip.itinerary[day]?.title}</h2></div><button onClick={addPlace} style={{background:th.p}} className="text-white p-2.5 rounded-xl"><Plus size={18}/></button></div><div className="flex gap-2 mb-4"><input value={newItem} onChange={e=>setNewItem(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addPlace()} placeholder="輸入景點、餐廳或咖啡廳" className="flex-1 rounded-xl border-0 px-4 py-3" style={{background:'#fff'}}/><button onClick={addPlace} style={{background:th.deep}} className="px-4 rounded-xl font-bold">加入</button></div>{(trip.itinerary[day]?.items||[]).map((x,i)=><Place key={i} x={x} th={th} city={trip.city}/>)}</section>:<Empty t="還沒有行程" s="可以建立旅行後開始安排。" th={th}/>}</div>}
function MapView({trip,th}){const places=trip.itinerary.flatMap(d=>d.items).filter(x=>x[2]!=='flight');return <div className="space-y-4"><Title t="旅行地圖" sub={`${places.length} 個行程地點`} th={th}/><section style={{background:th.card}} className="rounded-3xl p-4 shadow-sm"><div className="h-80 sm:h-[460px] rounded-2xl relative overflow-hidden" style={{background:'linear-gradient(135deg,#e8eee9,#f7f1e6,#dfe9ed)'}}>{places.slice(0,20).map((x,i)=><button key={i} onClick={()=>maps(x[1]+' '+trip.city)} className="absolute w-9 h-9 rounded-full shadow-md text-white flex items-center justify-center" style={{left:(7+(i*17)%84)+'%',top:(12+(i*23)%74)+'%',background:th.p}}><MapPin size={17}/></button>)}<div className="absolute left-4 top-4 bg-white/90 rounded-xl px-3 py-2 text-xs font-semibold">{trip.city}</div></div><p className="text-xs opacity-50 mt-3">點選地圖標記可開啟 Google Maps 導航。</p></section></div>}
function Expenses({trip,th,spent,add}){const cats=['美食','交通','住宿','購物','門票','美容','其他'];return <div className="space-y-4"><div className="flex items-center justify-between"><Title t="旅行花費" sub="以 TWD 記錄，分類管理" th={th}/><button onClick={add} style={{background:th.p}} className="text-white rounded-xl px-3 py-2 text-sm font-bold flex gap-1"><Plus size={16}/>新增</button></div><section style={{background:th.card}} className="rounded-3xl p-5 shadow-sm"><p className="text-sm opacity-55">總花費</p><p className="text-3xl font-bold mt-1">NT${money(spent)}</p><div className="flex flex-wrap gap-2 mt-4">{cats.map(c=>{const n=trip.expenses.filter(e=>e.cat===c).reduce((s,e)=>s+Number(e.amount),0);return <span key={c} className="px-3 py-2 rounded-xl text-xs bg-white/70">{c}　${money(n)}</span>})}</div></section>{trip.expenses.map(e=><div key={e.id} className="bg-white/80 rounded-2xl p-4 flex justify-between items-center"><div><p className="font-semibold">{e.title}</p><p className="text-xs opacity-50 mt-1">{e.cat}</p></div><p className="font-bold">NT${money(e.amount)}</p></div>)}</div>}
function More({trip,th,patch,toggle,setD,d}){const[section,setSection]=useState('shopping');return <div className="space-y-4"><Title t="更多工具" sub="旅行中常用的資訊集中管理" th={th}/><div className="grid grid-cols-3 gap-2">{[['shopping',ShoppingBag,'購物'],['check',CheckCircle2,'Checklist'],['stay',Hotel,'住宿'],['saved',Heart,'收藏'],['notes',NotebookPen,'筆記'],['settings',Settings,'設定']].map(([id,I,l])=><button key={id} onClick={()=>setSection(id)} style={{background:section===id?th.deep:'#fff'}} className="rounded-2xl p-4 flex flex-col items-center gap-2 text-sm"><I size={21}/>{l}</button>)}</div>{section==='shopping'&&<List title="購物清單" items={trip.shopping} th={th} add={v=>patch({shopping:[...trip.shopping,{id:Date.now(),title:v,done:false}]})} toggle={toggle} k="shopping"/>}{section==='check'&&<List title="行前 Checklist" items={trip.check} th={th} add={v=>patch({check:[...trip.check,{id:Date.now(),title:v,done:false}]})} toggle={toggle} k="check"/>}{section==='stay'&&<Stay trip={trip} th={th} patch={patch}/>} {section==='saved'&&<div className="space-y-2">{trip.saved.map(x=><div key={x.id} className="bg-white/80 rounded-2xl p-4 flex items-center gap-3"><Heart size={18} style={{color:th.p}}/><div><b>{x.title}</b><p className="text-xs opacity-50">{x.type}</p></div></div>)}{!trip.saved.length&&<Empty t="尚未收藏" s="把想去的地方留在這裡。" th={th}/>}</div>} {section==='notes'&&<textarea value={trip.notes||''} onChange={e=>patch({notes:e.target.value})} className="w-full min-h-64 rounded-3xl border-0 p-5 bg-white/80" placeholder="寫下旅行筆記、提醒、地址、密碼……"/>}{section==='settings'&&<SettingsPanel d={d} setD={setD} th={th}/>}</div>}
function List({title,items,th,add,toggle,k}){const[v,setV]=useState('');return <section style={{background:th.card}} className="rounded-3xl p-5 shadow-sm"><h2 className="text-xl font-bold mb-4">{title}</h2><div className="flex gap-2 mb-4"><input value={v} onChange={e=>setV(e.target.value)} placeholder="新增項目" className="flex-1 rounded-xl border-0 px-4 py-3 bg-white"/><button onClick={()=>{if(v.trim()){add(v.trim());setV('')}}} style={{background:th.p}} className="text-white px-4 rounded-xl"><Plus size={18}/></button></div><div className="space-y-2">{items.map(x=><button key={x.id} onClick={()=>toggle(k,x.id)} className="w-full bg-white/80 rounded-2xl p-4 flex items-center gap-3 text-left">{x.done?<CheckCircle2 size={20} style={{color:th.p}}/>:<Circle size={20}/>}<span className={x.done?'line-through opacity-45':''}>{x.title}</span></button>)}</div></section>}
function Stay({trip,th,patch}){const s=trip.stay||{};const save=(k,v)=>patch({stay:{...s,[k]:v}});return <section style={{background:th.card}} className="rounded-3xl p-5 shadow-sm space-y-3"><h2 className="text-xl font-bold">住宿資訊</h2>{[['name','住宿名稱'],['address','地址'],['in','Check-in'],['out','Check-out'],['wifi','Wi-Fi'],['door','門鎖密碼']].map(([k,p])=><Input key={k} p={p} v={s[k]||''} set={v=>save(k,v)}/>)}</section>}
function SettingsPanel({d,setD,th}){return <section style={{background:th.card}} className="rounded-3xl p-5 shadow-sm"><h2 className="text-xl font-bold mb-4">介面主題</h2><div className="grid grid-cols-2 gap-3">{Object.keys(THEMES).map(k=><button key={k} onClick={()=>setD(x=>({...x,theme:k}))} style={{background:THEMES[k].card,border:d.theme===k?'2px solid '+THEMES[k].p:'2px solid transparent'}} className="rounded-2xl p-4 text-left">{k==='milk'?'Milk Tea':k==='sage'?'Sage':k==='sky'?'Sky':'Butter'}</button>)}</div></section>}
function Place({x,th,city}){return <div className="flex gap-3 items-stretch"><div className="w-14 shrink-0 text-xs opacity-55 pt-3 text-right">{x[0]}</div><div style={{background:th.card}} className="flex-1 rounded-2xl p-4 shadow-sm flex items-center justify-between gap-3"><div><p className="font-bold">{x[1]}</p><p className="text-xs opacity-50 mt-1">{x[3]||x[2]}</p></div>{x[2]!=='flight'&&<button onClick={()=>maps(x[1]+' '+city)} className="p-2 rounded-xl bg-white"><Navigation size={17}/></button>}</div></div>}
function Quick({I,t,s,c,th}){return <button onClick={c} style={{background:th.card}} className="rounded-2xl p-4 text-left shadow-sm"><I size={20} style={{color:th.p}}/><p className="font-bold mt-3">{t}</p><p className="text-xs opacity-50 mt-1">{s}</p></button>}
function Stat({l,v}){return <div className="bg-white/55 rounded-2xl p-3"><p className="text-[11px] opacity-50">{l}</p><p className="font-bold mt-1 text-sm truncate">{v}</p></div>}
function Title({t,sub,action,c}){return <div className="flex items-end justify-between"><div><h2 className="text-xl font-bold">{t}</h2>{sub&&<p className="text-xs opacity-50 mt-1">{sub}</p>}</div>{action&&<button onClick={c} className="text-xs font-semibold opacity-60">{action}</button>}</div>}
function Input({p,v,set,type='text'}){return <input type={type} value={v} onChange={e=>set(e.target.value)} placeholder={p} className="w-full rounded-xl border-0 px-4 py-3 bg-white/90 outline-none"/>}
function Modal({title,close,children}){return <div className="fixed inset-0 z-50 bg-black/30 backdrop-blur-sm flex items-end sm:items-center justify-center p-3"><div className="bg-white w-full max-w-lg rounded-3xl p-5 max-h-[90vh] overflow-auto"><div className="flex items-center justify-between mb-5"><h2 className="text-xl font-bold">{title}</h2><button onClick={close} className="p-2 rounded-xl bg-gray-100"><X size={18}/></button></div>{children}</div></div>}
function Empty({t,s,th}){return <div style={{background:th.card}} className="rounded-3xl p-10 text-center shadow-sm"><p className="font-bold">{t}</p><p className="text-sm opacity-50 mt-1">{s}</p></div>}
